### ISSUE TITLE
Please provide Demo Website !

### ISSUE THREAD

**Issue by musky603** [ribeiroeder/jquery-feed-instagram-graph#1]
After checking out your coding and description I feel some ray of hope but please provide demo website if possible like this [ https://www.sowecms.com/demos/InstagramFeed/ ] would be great so that it becomes more easy to understand & implement.

**Comment by ribeiroeder** [comment]
Hello @musky603

Here you can find an example page of other users who are manipulating the script.

https://www.jqueryscript.net/demo/instagram-feed-graph-api/
